=== discospiff/PlantPlaces18FS001/PlantPlaces18FS001/PlantPlaces18FS001/plants.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="plant">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="genus">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:maxLength value="60"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:element>
        <xs:element name="species" minOccurs="0" default="spp.">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:maxLength value="60"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:element>
        <xs:element name="cultivar" minOccurs="0">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:maxLength value="60"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:element>
        <xs:element name="common_name" minOccurs="0">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:maxLength value="100"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:element>
        <xs:element name="height" minOccurs="0">
			<xs:simpleType>
				<xs:restriction base="xs:integer">
					<xs:minInclusive value="0"/>
					<xs:maxInclusive value="200"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:element>
		<xs:element name="begin_bloom_date" type="xs:date" minOccurs="0"/>
		<xs:element name="end_bloom_date" type="xs:date" minOccurs="0"/>
		<xs:element name="edible" type="xs:boolean" minOccurs="0"/>
		<xs:element name="sun_tolerance" minOccurs="0">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="full_sun"/>
					<xs:enumeration value="part_sun"/>
					<xs:enumeration value="part_shade"/>
					<xs:enumeration value="full_shade"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:element>
		<xs:element name="bloom_color" minOccurs="0">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="white"/>
					<xs:enumeration value="yellow"/>
					<xs:enumeration value="red"/>
					<xs:enumeration value="violet"/>
					<xs:enumeration value="blue"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:element>
  
		  <xs:element name="specimens">
			<xs:complexType>
			  <xs:sequence>
				<xs:element name="specimen" minOccurs="1" maxOccurs="unbounded" type="specimenType"/>
			  </xs:sequence>
			</xs:complexType>
		  </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>




    <xs:complexType name="specimenType">
      <xs:sequence>
        <xs:element name="latitude" type="xs:string"/>
        <xs:element name="longitude" type="xs:string"/>
        <xs:element name="description" type="xs:string"/>
        <xs:element name="planted_by" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>

</xs:schema>

=== discospiff/PlantPlaces18FS001/PlantPlaces18FS001/PlantPlaces18FS001/plants.xml
<?xml version="1.0" encoding="utf-8" ?>
<plant xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="plants.xsd"> 
  <genus>Asimina</genus>
  <species>triloba</species>
  <cultivar>Potomac</cultivar>
  <common_name>Pawpaw</common_name>
  <height>35</height>
  <begin_bloom_date>2018-04-01</begin_bloom_date>
  <end_bloom_date>2018-04-15</end_bloom_date>
  <edible>true</edible>
  <sun_tolerance>part_shade</sun_tolerance>
  <bloom_color>violet</bloom_color>
  <specimens>
    <specimen>
      <latitude>39.74</latitude>
      <longitude>-84.51</longitude>
      <description>A beautiful specimen in my yard, planted in 2008</description>
      <planted_by>Checkers</planted_by>
    </specimen>
    <specimen>
      <latitude>51.52</latitude>
      <longitude>-0.54</longitude>
      <description>RBG Kew</description>
      <planted_by>Bugsy</planted_by>
    </specimen>
    <specimen>
      <latitude>-25.63</latitude>
      <longitude>-52.36</longitude>
      <description>Brazil Botanic Gardens</description>
      <planted_by>Bugsy</planted_by>
    </specimen>
  </specimens>
</plant>
